version: '2'
services:

  rancher-server:
    image: rancher/server:v1.3.0
#    restart: unless-stopped
    volumes_from:
      - pinpoint-agent
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: "-javaagent:/assets/pinpoint-agent/pinpoint-bootstrap-1.8.0.jar -Dpinpoint.agentId=app-in-docker -Dpinpoint.applicationName=app"

  pinpoint-agent:
    image: proddam/pinpoint-agent:1.8.0
    network_mode: "none"
    restart: unless-stopped
    environment:
      COLLECTOR_IP: localhost
      COLLECTOR_TCP_PORT: 9994
      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
      PROFILER_SAMPLING_RATE: 1
      DISABLE_DEBUG: 'true'
