apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-web
  name: pinpoint-web
spec:
  type: NodePort
  ports:
  - name: "9997"
    port: 9997
    targetPort: 9997
    nodePort: 30186
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30086
  selector:
    io.kompose.service: pinpoint-web
status:
  loadBalancer: {}
