apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.15.0 (e3cd4d4)
  creationTimestamp: null
  labels:
    io.kompose.service: pinpoint-collector
  name: pinpoint-collector
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: pinpoint-collector
    spec:
      containers:
      - env:
        - name: CLUSTER_ENABLE
          value: "true"
        - name: CLUSTER_ZOOKEEPER_ADDRESS
          value: pinpoint-hbase
        - name: COLLECTOR_TCP_PORT
          value: "9994"
        - name: COLLECTOR_UDP_SPAN_LISTEN_PORT
          value: "9996"
        - name: COLLECTOR_UDP_STAT_LISTEN_PORT
          value: "9995"
        - name: DISABLE_DEBUG
          value: "true"
        - name: FLINK_CLUSTER_ENABLE
          value: "true"
        - name: FLINK_CLUSTER_ZOOKEEPER_ADDRESS
          value: pinpoint-hbase
        - name: HBASE_HOST
          value: pinpoint-hbase
        - name: HBASE_PORT
          value: "2181"
        image: proddam/pinpoint-collector:1.8.0
        imagePullPolicy: Always
        name: pinpoint-collector
        ports:
        - containerPort: 9994
        - containerPort: 9995
        - containerPort: 9996
        - containerPort: 9995
          protocol: UDP
        - containerPort: 9996
          protocol: UDP
        resources: {}
      hostname: collector
      restartPolicy: Always
status: {}
