version: '2'
services:

  pinpoint-hbase:
    container_name: pinpoint-hbase
    hostname: pinpoint-hbase
    image: proddam/pinpoint-hbase:1.8.0
    restart: always
    expose:
      - "2181"
      - "16010"
    ports:
      - "2181:2181"
      - "16010:16010"

  pinpoint-collector:
    container_name: pinpoint-collector
    hostname: collector
    image: proddam/pinpoint-collector:1.8.0
    depends_on:
      - pinpoint-hbase
    restart: always
    expose:
      - "9994"
      - "9995"
      - "9996"
    ports:
      - "9994:9994"
      - "9995:9995/tcp"
      - "9996:9996/tcp"
      - "9995:9995/udp"
      - "9996:9996/udp"
    environment:
      HBASE_HOST: pinpoint-hbase
      HBASE_PORT: 2181
      COLLECTOR_TCP_PORT: 9994
      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
      CLUSTER_ENABLE: 'true'
      CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      FLINK_CLUSTER_ENABLE: 'true'
      FLINK_CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      DISABLE_DEBUG: 'true'

  pinpoint-web:
    container_name: pinpoint-web
    hostname: web
    image: proddam/pinpoint-web:1.8.0
    depends_on:
      - pinpoint-hbase
    restart: always
    expose:
      - "8080"
      - "9997"
    ports:
      - "9997:9997"
      - "8181:8080"
    environment:
      HBASE_HOST: pinpoint-hbase
      HBASE_PORT: 2181
      CLUSTER_ENABLE: 'true'
      CLUSTER_ZOOKEEPER_ADDRESS: pinpoint-hbase
      CLUSTER_WEB_TCP_PORT: 9997
      ADMIN_PASSWORD: admin123
      DISABLE_ANALYTICS: 'true'
      ENABLE_APPLICATION_INSPECTOR: 'true'
      DISABLE_DEBUG: 'true'

  rancher-server:
    image: rancher/server:v1.3.0
    container_name: pinpoint-app
    depends_on:
      - pinpoint-agent
    volumes_from:
      - pinpoint-agent
    ports:
      - 18080:8080
    environment:
      JAVA_OPTS: "-javaagent:/assets/pinpoint-agent/pinpoint-bootstrap-1.8.0.jar -Dpinpoint.agentId=app-in-docker -Dpinpoint.applicationName=app"

  pinpoint-agent:
    container_name: pinpoint-agent
    depends_on:
      - pinpoint-collector
    image: proddam/pinpoint-agent:1.8.0
    network_mode: "none"
    environment:
      COLLECTOR_IP: pinpoint-collector
      COLLECTOR_TCP_PORT: 9994
      COLLECTOR_UDP_STAT_LISTEN_PORT: 9995
      COLLECTOR_UDP_SPAN_LISTEN_PORT: 9996
      PROFILER_SAMPLING_RATE: 1
      DISABLE_DEBUG: 'true'
